### ISSUE TITLE
Builds are failing on CI

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli-plugin-cna#41]
**Describe the bug**
See https://travis-ci.com/adobe/aio-cli-plugin-cna/jobs/246845745
Builds are failing on CI since this commit https://github.com/adobe/aio-cli-plugin-cna/commit/4d91c138a55822907d7b6f1a729bcc7b4fc7c0f6

**Problem**
`npm ci` needs a `package-lock.json` file: https://docs.npmjs.com/cli/ci.html

**Solution**
You will need to generate a `package-lock.json` file only, before calling `npm ci`.
Use:
`npm i --package-lock --package-lock-only`

This will generate the lock file only, and temporarily set the `package-lock` value in npm config / .npmrc to true (just in case it was set to false).

**Comment by purplecabbage** [comment]
fixed
